### ISSUE TITLE
Server started with exceptions

### ISSUE THREAD

**Issue by ekamw-dev** [ekamiddleware/ekamw-distributions#43]
Hi, 

I have downloaded the server with JDK and followed the instruction available at https://ekamw.org/video.html
Server has started fast but why is it throwing exceptions?
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.eka.middleware.template.SnippetException: java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "fqnOfMethod" is null
	at com.eka.middleware.service.DataPipeline.apply(DataPipeline.java:691)
	at packages.middleware.pub.service.utils.execute.main(execute.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.eka.middleware.server.ServiceManager.invokeJavaMethod(ServiceManager.java:78)
	at com.eka.middleware.service.DataPipeline.lambda$1(DataPipeline.java:742)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "fqnOfMethod" is null
	at com.eka.middleware.service.DataPipeline.apply(DataPipeline.java:666)

Thanks,

**Comment by ekamiddleware** [comment]
The issue is fixed. Download again and try. Please let us know the result.
